  
- hosts: servers
  connection: local
  gather_facts: false
  tasks:
    - name: App | Cloning repos + submodules
      git: repo=git@github.com:dench111/rest-service.git
           dest=/tmp/workspace/sources/
           accept_hostkey=yes
           force=yes
           recursive=no
           key_file=/home/root/.ssh/id_rsa.pub
    - name: check workspace dir
      shell:
        cmd: ls -l /tmp/workspace/sources/
    - name: build container image
      docker_image: >
        name=democontainer
        tag=v1
        path=/tmp/workspace/sources/Dockerfile
        state: present
